// moviesActions
export const FETCH_TRENDING = 'FETCH_TRENDING';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_ERROR = 'FETCH_TRENDING_ERROR';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const REMOVE_ID_FILTERED_MOVIES = 'REMOVE_ID_FILTERED_MOVIES';
export const SET_FILTERED_MOVIES = 'SET_FILTERED_MOVIES';
export const SET_MOVIES_FOUND = 'SET_MOVIES_FOUND';
export const SET_RESPONSE_ERROR_TRENDING = 'SET_RESPONSE_ERROR_TRENDING';
export const SET_RESPONSE_ERROR_SEARCH = 'SET_RESPONSE_ERROR_SEARCH';

// genresActions
export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_ERROR = 'FETCH_GENRES_ERROR';
export const SET_RESPONSE_ERROR_GENRES = 'SET_RESPONSE_ERROR_GENRES';
